exports.EquipmentController = require('./equipment');
exports.Resource = require('./resource/index');
exports.Automation = require('./automation/index');
exports.ProjectController = require('./project/index');
exports.OrderController = require('./order/index');

exports.Controller = {
  Flow: require('./flow'),
  Checkout: require('./checkout'),
  Card: require('./cards'),
  Pool: require('./pool'),
  PartnerSectors: require('./partner/partnerSectors'),
  PartnerTypes: require('./partner/partnerTypes'),
  Partners: require('./partner/partners'),
  Contacts: require('./contact/contacts'),
  contactSources: require('./contact/contactSources'),
  contactGenTypes: require('./contact/contactGenTypes'),
  ContactStages: require('./contact/contactStages'),
  ContactTypes: require('./contact/contactTypes'),
  States: require('./states'),
  Payroll: require('./payroll'),
  Jobs: require('./jobs'),
  ContactEvents: require('./contactEvents'),
  CommercialContacts: require('./commercialContacts'),
  Users: require('./users'),
  Products: require('./products'),
  Panels: require('./panels'),
  Dispositions: require('./dispositions'),
  Groups: require('./groups'),
  Auth: require('./auth'),
  Appointments: require('./appointments'),
  Roles: require('./roles'),
  App: require('./app'),
  Reports: require('./reports'),
  Canvassing: require('./canvassing'),
  Projects: require('./projects'),
  Options: require('./options'),
  HOA: require('./hoa'),
  Notes: require('./notes'),
  Documents: require('./documents'),
  DocumentTypes: require('./documentTypes'),
  ClosingFormTypes: require('./closingFormTypes'),
  ClosingFormStatuses: require('./closingFormStatuses'),
  Updates: require('./update'),
  PartnerProposals: require('./partnerProposals'),
  LenderProposals: require('./lenderProposals'),
  Incentives: require('./incentives'),
  Adders: require('./adders'),
  ClosingForms: require('./closingform/closingForms'),
  ClosingFormComments: require('./closingform/closingFormComments'),
  ClosingFormCommentTypes: require('./closingform/closingFormCommentTypes'),
  Teams: require('./teams'),
  Lenders: require('./lenders'),
  Zones: require('./zones'),
  Utilities: require('./utilities'),
  Integrations: require('./integrations'),
  RoofTypes: require('./roofTypes'),
  PropertyTypes: require('./propertyTypes'),
  UtilityProviders: require('./utilityProviders'),
  External: require('./external'),
  Logins: require('./logins'),
  ApiKeys: require('./apiKeys'),
  Organizations: require('./organizations')
};
